<div class="alert alert-block alert-info">
<h2>Daftar Isi: </h2>
    <ol>
    <li>Memuat Data</li>
    <li>Menelaah Data</li>
    </ol>
</div>

<div class="alert alert-block alert-danger">
<b>Catatan : </b>Jika belum pernah instal library, gunakan perintah berikut secara inline atau melalui terminal.
    <ol>
    <li>!pip install pandas</li>
    <li>!pip install numpy</li>
    </ol>
</div>

## Memuat Data
---

In [ ]:
# !pip install pandas

In [ ]:
# import library
import pandas as pd
import numpy as np

In [ ]:
# load dataset
path = "epl-goalScorer(20-21).csv"
df = pd.read_csv(path)

In [ ]:
# menampilkan 5 baris awal dari dataset
df.head()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,0,647,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,1,1250,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,2,1228,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,3,453,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,4,822,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796

In [ ]:
# menampilkan 5 baris akhir dari dataset
df.tail()

,Unnamed: 0,id,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
517,517,9415,Jaden Philogene-Bidace,1,1,0,0.000000,0,0.0,0,0,0,0,S,Aston Villa,0,0.000000,0.056044,0.056044
518,518,9423,Gaetano Berardi,2,113,0,0.074761,0,0.0,1,0,0,0,D S,Leeds,0,0.074761,0.231278,0.231278
519,519,9524,Anthony Elanga,1,67,0,0.000000,0,0.0,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
520,520,9540,Femi Seriki,1,1,0,0.000000,0,0.0,0,0,0,0,S,Sheffield United,0,0.000000,0.000000,0.000000
521,521,9552,Tyrese Francois,1,13,0,0.000000,0,0.0,0,0,0,0,S,Fulham,0,0.000000,0.000000,0.000000

## Menelaah Data
---

In [ ]:
# mengungkap tipe-tipe data dari setiap kolom
print(df.dtypes)

Unnamed: 0        int64
id                int64
player_name      object
games             int64
time              int64
goals             int64
xG              float64
assists           int64
xA              float64
shots             int64
key_passes        int64
yellow_cards      int64
red_cards         int64
position         object
team_title       object
npg               int64
npxG            float64
xGChain         float64
xGBuildup       float64
dtype: object

Dari hasil output diatas terlihat bahwa 2 kolom pertama (yaitu: 'Unnamed: 0', dan 'id') hanyalah data numerik yang biasanya tidak memiliki makna rill, sehingga kita bisa tidak gunakan kolom/field tsb.

In [ ]:
df_noid = df.iloc[:,2:]
df_noid

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
0,Harry Kane,35,3097,23,22.174859,14,7.577094,138,49,1,0,F,Tottenham,19,19.130183,24.995648,4.451257
1,Mohamed Salah,37,3085,22,20.250847,5,6.528526,126,55,0,0,F M S,Liverpool,16,15.683834,28.968234,9.800236
2,Bruno Fernandes,37,3117,18,16.019454,12,11.474996,121,95,6,0,M S,Manchester United,9,8.407840,26.911412,11.932285
3,Son Heung-Min,37,3139,17,11.023287,10,9.512992,68,75,0,0,F M S,Tottenham,16,10.262118,20.671916,6.608751
4,Patrick Bamford,38,3085,17,18.401863,7,3.782247,107,30,3,0,F S,Leeds,15,16.879525,23.394953,4.131796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,Jaden Philogene-Bidace,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Aston Villa,0,0.000000,0.056044,0.056044
518,Gaetano Berardi,2,113,0,0.074761,0,0.000000,1,0,0,0,D S,Leeds,0,0.074761,0.231278,0.231278
519,Anthony Elanga,1,67,0,0.000000,0,0.000000,0,0,0,0,M,Manchester United,0,0.000000,0.000000,0.000000
520,Femi Seriki,1,1,0,0.000000,0,0.000000,0,0,0,0,S,Sheffield United,0,0.000000,0.000000,0.000000
521,Tyrese Francois,1,13,0,0.000000,0,0.000000,0,0,0,0,S,Fulham,0,0.000000,0.000000,0.000000

In [ ]:
# menampilkan statistik dasar setiap kolom data yang bertipe numerik.
df_noid.describe()

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
count,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000
mean,19.643678,1420.068966,1.862069,2.000806,1.289272,1.376029,17.379310,12.963602,2.061303,0.091954,1.668582,1.821450,5.663368,3.455060
std,11.619836,1031.604819,3.338851,3.317946,2.083350,1.886510,21.572664,16.164361,2.203661,0.295800,2.909929,2.931176,5.600249,3.376584
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,10.000000,470.250000,0.000000,0.074668,0.000000,0.049245,2.000000,1.000000,0.000000,0.000000,0.000000,0.074668,1.191391,0.720353
50%,21.000000,1342.000000,1.000000,0.737295,0.000000,0.691122,10.000000,7.000000,2.000000,0.000000,0.500000,0.715585,4.252738,2.656397
75%,30.000000,2319.000000,2.000000,2.053378,2.000000,2.050509,23.750000,19.000000,3.000000,0.000000,2.000000,1.945799,8.308002,5.254647
max,38.000000,3420.000000,23.000000,22.174859,14.000000,11.474996,138.000000,95.000000,12.000000,2.000000,19.000000,19.130183,28.968234,18.323006

In [ ]:
# jika ingin menampilkan juga statistik kolom-
# yang bertipe non-numerik, mencakup beberapa banyak nilai unik-
# dalam kolom (unique), nilai modus(top), serta frekuensi modus(freq)
df_noid.describe(include="all")

,player_name,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,position,team_title,npg,npxG,xGChain,xGBuildup
count,522,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522.000000,522,522,522.000000,522.000000,522.000000,522.000000
unique,522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,28,NaN,NaN,NaN,NaN
top,Tyrese Francois,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M S,Everton,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106,28,NaN,NaN,NaN,NaN
mean,NaN,19.643678,1420.068966,1.862069,2.000806,1.289272,1.376029,17.379310,12.963602,2.061303,0.091954,NaN,NaN,1.668582,1.821450,5.663368,3.455060
std,NaN,11.619836,1031.604819,3.338851,3.317946,2.083350,1.886510,21.572664,16.164361,2.203661,0.295800,NaN,NaN,2.909929,2.931176,5.600249,3.376584
min,NaN,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,0.000000,0.000000,0.000000
25%,NaN,10.000000,470.250000,0.000000,0.074668,0.000000,0.049245,2.000000,1.000000,0.000000,0.000000,NaN,NaN,0.000000,0.074668,1.191391,0.720353
50%,NaN,21.000000,1342.000000,1.000000,0.737295,0.000000,0.691122,10.000000,7.000000,2.000000,0.000000,NaN,NaN,0.500000,0.715585,4.252738,2.656397
75%,NaN,30.000000,2319.000000,2.000000,2.053378,2.000000,2.050509,23.750000,19.000000,3.000000,0.000000,NaN,NaN,2.000000,1.945799,8.308002,5.254647
max,NaN,38.000000,3420.000000,23.000000,22.174859,14.000000,11.474996,138.000000,95.000000,12.000000,2.000000,NaN,NaN,19.000000,19.130183,28.968234,18.323006

### Contoh fungsi statistik setiap kolom (yang applicable)
---

In [ ]:
df_noid.select_dtypes(include='number').mean()

games             19.643678
time            1420.068966
goals              1.862069
xG                 2.000806
assists            1.289272
xA                 1.376029
shots             17.379310
key_passes        12.963602
yellow_cards       2.061303
red_cards          0.091954
npg                1.668582
npxG               1.821450
xGChain            5.663368
xGBuildup          3.455060
dtype: float64

In [ ]:
df_noid.sum()

player_name     Harry KaneMohamed SalahBruno FernandesSon Heun...
games                                                       10254
time                                                       741276
goals                                                         972
xG                                                    1044.420572
assists                                                       673
xA                                                     718.287269
shots                                                        9072
key_passes                                                   6767
yellow_cards                                                 1076
red_cards                                                      48
position        FF M SM SF M SF SF SF SFM SF M SF SF SF SF SF ...
team_title      TottenhamLiverpoolManchester UnitedTottenhamLe...
npg                                                           871
npxG                                                     950.7971
xGChain                                               2956.278233
xGBuildup                                             1803.541131
dtype: object

In [ ]:
df_noid.select_dtypes(include='number').median()

games             21.000000
time            1342.000000
goals              1.000000
xG                 0.737295
assists            0.000000
xA                 0.691122
shots             10.000000
key_passes         7.000000
yellow_cards       2.000000
red_cards          0.000000
npg                0.500000
npxG               0.715585
xGChain            4.252738
xGBuildup          2.656397
dtype: float64

In [ ]:
df_noid.std(numeric_only=True)

games             11.619836
time            1031.604819
goals              3.338851
xG                 3.317946
assists            2.083350
xA                 1.886510
shots             21.572664
key_passes        16.164361
yellow_cards       2.203661
red_cards          0.295800
npg                2.909929
npxG               2.931176
xGChain            5.600249
xGBuildup          3.376584
dtype: float64

In [ ]:
df_noid.quantile(0.75)

### Mencari pencilan dengan Tukey's fences (1)
---

In [ ]:
q1 = df_noid.quantile(0.25, numeric_only=True)
q3 = df_noid.quantile(0.75, numeric_only=True)

iqr = q3 - q1

print(iqr)

games             20.000000
time            1848.750000
goals              2.000000
xG                 1.978711
assists            2.000000
xA                 2.001264
shots             21.750000
key_passes        18.000000
yellow_cards       3.000000
red_cards          0.000000
npg                2.000000
npxG               1.871131
xGChain            7.116612
xGBuildup          4.534294
dtype: float64

### Mencari pencilan dengan Tukey's fences (2)
---

In [ ]:
import warnings
warnings.filterwarnings('ignore')

# ambil hanya kolom numerik
df_num = df_noid.select_dtypes(include='number')

# hitung Q1, Q3, IQR
q1 = df_num.quantile(0.25)
q3 = df_num.quantile(0.75)
iqr = q3 - q1

# filter outlier
outlier_filter = (df_num < (q1 - 1.5 * iqr)) | (df_num > (q3 + 1.5 * iqr))

outlier_filter

,games,time,goals,xG,assists,xA,shots,key_passes,yellow_cards,red_cards,npg,npxG,xGChain,xGBuildup
0,False,False,True,True,True,True,True,True,False,False,True,True,True,False
1,False,False,True,True,False,True,True,True,False,False,True,True,True,False
2,False,False,True,True,True,True,True,True,False,False,True,True,True,False
3,False,False,True,True,True,True,True,True,False,False,True,True,True,False
4,False,False,True,True,True,False,True,False,False,False,True,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517,False,False,False,False,False,False,False,False,False,False,False,False,False,False
518,False,False,False,False,False,False,False,False,False,False,False,False,False,False
519,False,False,False,False,False,False,False,False,False,False,False,False,False,False
520,False,False,False,False,False,False,False,False,False,False,False,False,False,False
521,False,False,False,False,False,False,False,False,False,False,False,False,False,False

### Mencari pencilan dengan Tukey's fences (3)
---

In [ ]:
df_noid[outlier_filter['assists']] \
    .loc[:, ['player_name', 'assists']] \
    .sort_values(by=['assists'], ascending=False)

                player_name  assists
0                Harry Kane       14
2           Bruno Fernandes       12
58          Kevin De Bruyne       11
51            Jack Grealish       10
3             Son Heung-Min       10
6               Jamie Vardy        9
15          Marcus Rashford        9
57                 Raphinha        9
41            Jack Harrison        8
83              Pascal Groß        8
49              Timo Werner        8
281         Aaron Cresswell        8
130  Trent Alexander-Arnold        7
358             Lucas Digne        7
32        James Ward-Prowse        7
16               Sadio Mané        7
4           Patrick Bamford        7
26          Roberto Firmino        7
204        Andrew Robertson        7
18          Matheus Pereira        6
22          Raheem Sterling        6
42          Bertrand Traoré        6
62               Pedro Neto        6
79             Eberechi Eze        6
137          Bernardo Silva        6
211           Said Benrahma        6
495         Vladimir Coufal        6

### Value_counts()
---
menghasilkan frekuensi setiap nilai unik di dalam kolom, yang tertinggi count-nya merupakan modus pada kolom tsb. Ada data dengan dua/tiga nama tim karena ada pemain yang bermain di dua/tiga klub dalam musim yang sama(ada transfer pemain)

In [ ]:
df_noid['team_title'].value_counts()

team_title
Everton                          28
West Bromwich Albion             28
Leicester                        27
Liverpool                        27
Southampton                      27
Sheffield United                 27
Wolverhampton Wanderers          27
Manchester United                27
Fulham                           27
Arsenal                          26
Newcastle United                 26
Brighton                         26
Burnley                          25
Chelsea                          25
Tottenham                        24
Manchester City                  24
Crystal Palace                   24
Leeds                            23
Aston Villa                      23
West Ham                         23
Arsenal,Newcastle United          1
Everton,Southampton               1
Aston Villa,Chelsea               1
Liverpool,Southampton             1
Chelsea,Fulham                    1
West Bromwich Albion,West Ham     1
Arsenal,West Bromwich Albion      1
Arsenal,Brighton                  1
Name: count, dtype: int64

### Analisis dengan groupby
---
method groupby memungkinkan analisa dilakukan secara per kelompok nilai atribut tertentu.
misal: rerata dan simpangan baku gol per tim

In [ ]:
df.groupby('team_title')['goals'].std()

team_title
Arsenal                          3.352381
Arsenal,Brighton                      NaN
Arsenal,Newcastle United              NaN
Arsenal,West Bromwich Albion          NaN
Aston Villa                      3.696489
Aston Villa,Chelsea                   NaN
Brighton                         2.158703
Burnley                          2.475210
Chelsea                          2.350177
Chelsea,Fulham                        NaN
Crystal Palace                   2.901461
Everton                          3.467727
Everton,Southampton                   NaN
Fulham                           1.439175
Leeds                            4.153193
Leicester                        4.020602
Liverpool                        4.931439
Liverpool,Southampton                 NaN
Manchester City                  3.867132
Manchester United                4.317855
Newcastle United                 2.483174
Sheffield United                 1.467599
Southampton                      3.141941
Tottenham                        5.855135
West Bromwich Albion             2.310260
West Bromwich Albion,West Ham         NaN
West Ham                         3.369240
Wolverhampton Wanderers          1.648620
Name: goals, dtype: float64

In [ ]:
df.groupby('team_title')['goals'].mean()

### Korelasi Pearson antara kolom-kolom numerik
---
* Method corr() menghasilkan tabel korelasi pearson antar kolom-kolom numerik.
* Rentang nilai: antara -1 dan 1
* -1 = korelasi negatif | 0 = tidak ada korelasi linier | +1 = korelasi positif

In [ ]:
df_noid.loc[:,'games':].corr()